const { readFileSync } = require("node:fs")
const { test } = require("node:test")
const assert = require("node:assert/strict")
const path = require("node:path")

const source = readFileSync(path.join(__dirname, "page.tsx"), "utf8")

test("landing page keeps the focused Saathi entry hierarchy", () => {
  assert.match(source, /Make progress<br \/>visible\./)
  assert.match(source, /A focused workspace for teams to plan clearly, move together, and finish what matters\./)
  assert.match(source, /FROM INTENTION TO EXECUTION/)
  assert.match(source, /Create your workspace/)
  assert.match(source, /Explore the guide/)
  assert.match(source, /href="\/login"/)
  assert.match(source, /href="\/register"/)
  assert.match(source, /Clear next steps/)
  assert.match(source, /Shared ownership/)
  assert.match(source, /Visible progress/)
  assert.doesNotMatch(source, /Command center|Live engine|SSE task updates/)
})
