import http from 'k6/http';
import { check, sleep, group } from 'k6';
import { Counter, Trend, Gauge } from 'k6/metrics';

// Custom metrics
const createTaskDuration = new Trend('create_task_duration');
const updateTaskDuration = new Trend('update_task_duration');
const sseConnectionLatency = new Trend('sse_connection_latency');
const concurrentUsers = new Gauge('concurrent_users');
const taskOperations = new Counter('task_operations');

// Test configuration
export const options = {
  stages: [
    { duration: '30s', target: 50 },    // Ramp-up to 50 users
    { duration: '1m', target: 100 },    // Increase to 100 users
    { duration: '1m', target: 150 },    // Increase to 150 users
    { duration: '1m', target: 200 },    // Peak at 200 users
    { duration: '30s', target: 100 },   // Ramp-down to 100 users
    { duration: '30s', target: 0 },     // Ramp-down to 0 users
  ],
  thresholds: {
    http_req_duration: ['p(95)<500', 'p(99)<1000'], // 95% under 500ms, 99% under 1s
    http_req_failed: ['rate<0.1'], // Error rate below 10%
  },
};

const BASE_URL = __ENV.BASE_URL || 'http://localhost:3000';
const DEMO_EMAIL = 'demo@saathi.build';
const DEMO_PASSWORD = 'demo';

// Helper to get auth token
function getAuthToken() {
  const loginPayload = JSON.stringify({
    email: DEMO_EMAIL,
    password: DEMO_PASSWORD,
  });

  const params = {
    headers: {
      'Content-Type': 'application/json',
    },
  };

  const response = http.post(`${BASE_URL}/api/auth/login`, loginPayload, params);
  
  if (response.status === 200) {
    // Extract session from cookies
    return response.cookies;
  }
  
  return null;
}

// Main test function
export default function (data) {
  const userId = `user-${__VU}-${__ITER}`;
  
  group('Authentication', function () {
    // Login
    const loginPayload = JSON.stringify({
      email: `test${__VU}@test.com`,
      password: 'password123',
    });

    const params = {
      headers: {
        'Content-Type': 'application/json',
      },
    };

    const loginResponse = http.post(`${BASE_URL}/api/auth/login`, loginPayload, params);
    check(loginResponse, {
      'login successful': (r) => r.status === 200 || r.status === 401,
    });
  });

  // Update concurrent users metric
  concurrentUsers.add(__VU);

  group('Workspace Operations', function () {
    // Get workspaces
    const wsResponse = http.get(`${BASE_URL}/api/workspaces`, {
      headers: {
        'Accept': 'application/json',
      },
    });

    check(wsResponse, {
      'get workspaces': (r) => r.status === 200 || r.status === 401,
    });
  });

  group('Task Operations', function () {
    const taskPayload = JSON.stringify({
      title: `Load Test Task ${__VU}-${__ITER}`,
      description: 'Generated by k6 load test',
      workspaceId: 'test-workspace',
    });

    const params = {
      headers: {
        'Content-Type': 'application/json',
      },
    };

    // Create task
    const createStart = new Date();
    const createResponse = http.post(`${BASE_URL}/api/tasks`, taskPayload, params);
    const createDuration = new Date() - createStart;
    
    check(createResponse, {
      'create task': (r) => r.status === 200 || r.status === 201 || r.status === 400 || r.status === 401,
    });

    if (createResponse.status === 200 || createResponse.status === 201) {
      createTaskDuration.add(createDuration);
      taskOperations.add(1);

      // Try to parse response to get task ID
      try {
        const taskData = createResponse.json();
        if (taskData && taskData.id) {
          // Update task
          const updatePayload = JSON.stringify({
            title: `Updated Task ${__VU}-${__ITER}`,
            completed: false,
          });

          const updateStart = new Date();
          const updateResponse = http.put(`${BASE_URL}/api/tasks/${taskData.id}`, updatePayload, params);
          const updateDuration = new Date() - updateStart;

          check(updateResponse, {
            'update task': (r) => r.status === 200 || r.status === 400 || r.status === 401 || r.status === 404,
          });

          if (updateResponse.status === 200) {
            updateTaskDuration.add(updateDuration);
            taskOperations.add(1);
          }

          // Delete task
          const deleteResponse = http.delete(`${BASE_URL}/api/tasks/${taskData.id}`, params);
          check(deleteResponse, {
            'delete task': (r) => r.status === 200 || r.status === 204 || r.status === 400 || r.status === 401 || r.status === 404,
          });

          if (deleteResponse.status === 200 || deleteResponse.status === 204) {
            taskOperations.add(1);
          }
        }
      } catch (e) {
        console.log('Failed to parse task response:', e);
      }
    }
  });

  group('Real-time SSE Connection', function () {
    const sseStart = new Date();
    
    const sseResponse = http.get(`${BASE_URL}/api/realtime?workspaceId=test-workspace`, {
      headers: {
        'Accept': 'text/event-stream',
      },
      timeout: '5s',
    });

    const sseLatency = new Date() - sseStart;

    check(sseResponse, {
      'sse connection established': (r) => r.status === 200 || r.status === 401,
    });

    if (sseResponse.status === 200) {
      sseConnectionLatency.add(sseLatency);
      check(sseResponse, {
        'sse returns event stream': (r) => r.headers['Content-Type'].includes('text/event-stream'),
      });
    }
  });

  sleep(1);
}

// Teardown function to report results
export function teardown(data) {
  console.log('Load test completed. Check metrics in console output.');
}
